### ISSUE TITLE
DMで受けたコマンドを 無視 or いい感じ にしたい

### ISSUE THREAD

**Issue by tanakanata** [tanakanata/NewPants#13]

**Comment by naari3** [comment]
具体的な要望はわからないが、guild_onlyというデコレータがあるのでこれで該当コマンドをラップするだけで良さそう

https://discordpy.readthedocs.io/ja/latest/ext/commands/api.html#discord.ext.commands.guild_only

**Comment by naari3** [comment]
ref. https://discordpy.readthedocs.io/ja/latest/ext/commands/commands.html
```py
@guild_only()
async def test(ctx):
    await ctx.send('Hey this is not a DM! Nice.')

@test.error
async def test_error(ctx, error):
    if isinstance(error, NoPrivateMessages):
        await ctx.send(error)
```

もしもう少し細かいことがやりたいなら `@guild_only` デコレータを自作するのもアリ

**Comment by tanakanata** [comment]
前回のコミットで直したつもりでcloseしたが直ってなかったのでReopen

**Comment by tanakanata** [comment]
GithubにPushして満足してPullするのを忘れていただけで、コードに問題はなかった。
自分がGit初心者だった。
反省しています。
