### ISSUE TITLE
画像をremove.bgを利用して切り抜き結果を返す

### ISSUE THREAD

**Issue by yu0104** [tanakanata/NewPants#20]
APIがあるのでそれを利用
https://www.remove.bg/

**Comment by naari3** [comment]
愚直にAPIを叩くと月50回までの制限がある
https://www.remove.bg/pricing

誰かが金を払うか、ブラウザで試すときに触るAPIをむりやり叩く必要がある

**Comment by yu0104** [comment]
discordで通話した時に月50回だったらサーバーの規模的に問題ないかなぁと思ってるんだけど、
判断はたなかさんに任せます。

**Comment by yu0104** [comment]
月50でいいっていってたのでやります
